config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/search" => "pages#search", as: "search_page"
    get "/filter" => "pages#filter_via_brand"
    resources :brands, except: [:destroy, :show]
    resources :products, only: [:index, :show]
    resources :comments, only: [:create]
    resources :users, only: [:show]
    namespace :admin do
      get "/home", to: "static_pages#home"
      resources :brands, except: [:destroy, :show]
      resources :products, except: [:destroy, :show]
    end
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  belongs_to :size
  has_many :comments, dependent: :destroy
  scope :order_by_create, ->{order created_at: :desc}
  scope :order_by_update, ->{order updated_at: :desc}
  delegate :name, to: :brand, prefix: true, allow_nil: true
  delegate :name, to: :size, prefix: true, allow_nil: true
  scope :search_by_name, ->(key){where("name LIKE ?", "%#{key}%")}
  has_one_attached :image

  validates :name, presence: true,
    length: {maximum: Settings.product.max_name}
  validates :price, presence: true,
    length: {maximum: Settings.product.max_price}

  def display_image
    image.variant(resize_to_limit: [Settings.product.limit_img,
      Settings.product.limit_img])
  end

  def feed
    comments.created_at_desc
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :load_product, except: %i(index new create)

  def index
    @products = Product.order_by_update.order_by_create
                       .page(params[:page]).per(Settings.paging.p_10)
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    @product.image.attach(params[:product][:image])
    if @product.save
      flash[:info] = t "product.create_notification_success"
      redirect_to admin_products_path
    else
      flash.now[:danger] = t "product.create_notification_fail"
      render :new
    end
  end

  def edit; end

  def update
    if @product.update product_params
      flash[:success] = t "product.update_success"
      redirect_to admin_products_path
    else
      render :edit
    end
  end

  private

  def product_params
    params.require(:product).permit(:name, :price, :brand_id, :size_id,
                                    :describe, :image)
  end

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t "product.product_not_found"
    redirect_to root_path
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_product, only: [:show]

  def index
    @per_page = Settings.paging.p_8
    @products = Product.order_by_create.page(params[:page]).per(@per_page)
  end

  def show
    @comments = @product.feed.page(params[:page]).per(Settings.paging.p_5)
    @comment = @product.comments.build
  end

  private

  def load_product
    @product = Product.find_by id: params[:id]
    return if @product

    flash[:danger] = t "controllers.products_controller.product_not_found"
    redirect_to root_path
  end
end

app/helpers/products_helper.rb
module ProductsHelper
  def load_brands
    Brand.select(:id, :name)
  end

  def load_sizes
    Size.select(:id, :name)
  end
end

app/views/admin/products/_form_product.html.erb
<div class="col-md-6 offset-md-3">
  <%= form_for [:admin, @product] do |f| %>
    <%= render "shared/error_messages", object: f.object %>

    <div class="form-group row">
      <%= f.label :name, t("product.name") %>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="form-group row">
      <%= f.label :price, t("product.price") %>
      <%= f.text_field :price, class: "form-control" %>
    </div>

    <div class="form-group row">
      <%= f.label :brand, t("product.brand") %>
      <%= f.collection_select :brand_id, load_brands, :id, :name, {}, {class: "form-control"} %>
    </div>

    <div class="form-group row">
      <%= f.label :size, t("product.size") %>
      <%= f.collection_select :size_id, load_sizes, :id, :name, {}, {class: "form-control"} %>
    </div>

    <div class="form-group row">
      <%= f.label :describe, t("product.describe") %>
      <%= f.text_area :describe, class: "form-control" %>
    </div>

    <div class="form-group row">
      <%= image_tag @product.display_image if @product.image.attached? %>
      <%= f.label :image, t("product.image") %>
      <%= f.file_field :image, accept: Settings.product.accept_image, class: "form-control" %>
    </div>

    <div class= "form-group d-flex justify-content-center">
      <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    </div>
  <% end %>
</div>

app/views/admin/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= number_to_currency(product.price) %></td>
  <td><%= product.brand_name %></td>
  <td><%= product.size_name %></td>
  <td><%= product.describe %></td>
  <td><%= link_to t("product.show"), "#" %></td>
  <td><%= link_to t("product.edit"), edit_admin_product_path(product) %></td>
  <td><%= link_to t("product.destroy"), "#" %></td>
</tr>

app/views/admin/products/edit.html.erb
<div class= "d-flex justify-content-center">
  <h1><%= t("product.update_product")%></h1>
</div>

<% provide :button_text, t("product.update") %>
<%= render "form_product" %>
<%= link_to t("product.back"), admin_products_path %>

app/views/admin/products/index.html.erb
<div class= "container-fluid">
  <h1 class= "d-flex justify-content-between">
    <span><%= t "product.title" %></span>
    <%= link_to t("product.new_product"), new_admin_product_path, class: "btn btn-primary" %>
  </h1>

  <div class= "row mt-3 px-3">
    <table class="table table-striped mt-3">
      <thead>
        <tr>
          <th><%= t "product.name" %></th>
          <th><%= t "product.price" %></th>
          <th><%= t "base.brand" %></th>
          <th><%= t "base.size" %></th>
          <th><%= t "product.describe" %></th>
        </tr>
      </thead>
      <tbody>
        <%= render @products %>
      </tbody>
    </table>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class= "d-flex justify-content-center">
  <h1><%= t "product.new_product" %></h1>
</div>

<% provide :button_text, t("product.submit") %>
<%= render "form_product" %>
<%= link_to t("product.back"), admin_products_path %>