config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/search" => "pages#search", as: "search_page"
    get "/filter" => "pages#filter_via_brand"
    resources :brands, except: [:destroy, :show]
    resources :products, only: [:index, :show]
    resources :comments, only: [:create]
    resources :users, only: [:show]
    namespace :admin do
      get "/home", to: "static_pages#home"
      resources :brands, except: [:destroy, :show]
      resources :products, except: [:destroy, :show]
    end
  end
end

app/views/admin/layouts/_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder = "<%= t("base.search") %>"
        aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form>

  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#">
        <i class="fas fa-bell fa-fw"></i>
        <span class="badge badge-danger badge-counter"><%= t ".notification" %></span>
      </a>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#">
        <i class="fas fa-envelope fa-fw"></i>
        <span class="badge badge-danger badge-counter"><%= t ".message" %></span>
      </a>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.name %></span>
        <%= image_tag("admin/undraw_profile.svg", alt: "logo 1",
          class: "img-profile rounded-circle") %>
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
        aria-labelledby="userDropdown">
        <%= link_to t("base.profile"), current_user, class: "dropdown-item" %>
        <div class="dropdown-divider"></div>
        <%= link_to t("base.logout"), logout_path, class: "dropdown-item", method: "delete" %>
      </div>
    </li>
  </ul>
</nav>

app/views/admin/layouts/_left_menu.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <%= link_to t(".shop"), admin_home_path, class: "sidebar-brand d-flex align-items-center" %>

  <hr class="sidebar-divider">
  <div class="sidebar-heading"><%= t ".product_management" %></div>

  <li class="nav-item">
    <%= link_to t("base.product"), admin_products_path, class: "nav-link collapsed" %>
  </li>
  <li class="nav-item">
    <%= link_to t("base.brand"), admin_brands_path, class: "nav-link collapsed" %>
  </li>
  <li class="nav-item">
    <%= link_to t("base.size"), "#", class: "nav-link collapsed" %>
  </li>

  <hr class="sidebar-divider">
  <div class="sidebar-heading"><%= t ".business_management" %></div>

  <li class="nav-item">
    <%= link_to t("base.order"), "#", class: "nav-link collapsed" %>
  </li>

  <li class="nav-item">
    <%= link_to t(".statistical"), "#", class: "nav-link collapsed" %>
  </li>

  <hr class="sidebar-divider">
  <div class="sidebar-heading"><%= t ".account_management" %></div>

  <li class="nav-item">
    <%= link_to t("base.account"), "#", class: "nav-link collapsed" %>
  </li>
</ul>

app/views/admin/layouts/_main.html.erb
<div id="wrapper">
  <%= render "admin/layouts/left_menu" %>
  <div id="content-wrapper" class="d-flex flex-column">
    <div id="content">
      <%= render "admin/layouts/header" %>
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <div class="pb-3">
        <%= yield %>
      </div>
    </div>
  </div>
</div>