config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "static_pages#home"
    get "/about", to: "static_pages#about"
    get "/contact", to: "static_pages#contact"
    get "/login", to: "sessions#new"
    post "/login", to: "sessions#create"
    delete "/logout", to: "sessions#destroy"
    get "/search" => "pages#search", as: "search_page"
    get "/filter" => "pages#filter_via_brand"
    resources :brands, except: [:destroy, :show]
    resources :products, only: [:index, :show]
    resources :comments, only: [:create]
    resources :users, only: [:show]
    namespace :admin do
      get "/home", to: "static_pages#home"
      resources :brands, except: [:destroy, :show]
      resources :products, except: [:destroy, :show]
    end
  end
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products, dependent: :destroy
  validates :name, presence: true,
    length: {maximum: Settings.brand.name.max_length},
    uniqueness: {case_sensitive: false}
  scope :order_name_asc, ->{order :name}
end

app/controllers/admin/brands_controller.rb
class Admin::BrandsController < AdminController
  before_action :load_brand, only: [:edit, :update]

  def index
    @per_page = Settings.paging.p_10
    @brands = Brand.order_name_asc.page(params[:page]).per(@per_page)
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new brand_params
    if @brand.save
      flash[:success] = t "brands.brand_created"
      redirect_to admin_brands_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @brand.update(brand_params)
      flash[:success] = t "brands.brand_updated"
      redirect_to admin_brands_path
    else
      render :edit
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

  def load_brand
    @brand = Brand.find_by(id: params[:id])
    return if @brand

    flash[:warning] = t "brands.brand_not_found"
    redirect_to brands_path
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  before_action :load_brand, only: [:edit, :update]

  def index
    @per_page = Settings.paging.p_10
    @brands = Brand.order_name_asc.page(params[:page]).per(@per_page)
  end

  def new
    @brand = Brand.new
  end

  def create
    @brand = Brand.new brand_params
    if @brand.save
      flash[:success] = t "brands.brand_created"
      redirect_to brands_path
    else
      render :new
    end
  end

  def edit; end

  def update
    if @brand.update(brand_params)
      flash[:success] = t "brands.brand_updated"
      redirect_to brands_path
    else
      render :edit
    end
  end

  private

  def brand_params
    params.require(:brand).permit(:name)
  end

  def load_brand
    @brand = Brand.find_by(id: params[:id])
    return if @brand

    flash[:warning] = t "brands.brand_not_found"
    redirect_to brands_path
  end
end

app/views/brands/edit.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-3">
      <div class="card">
        <div class="card-header bg-primary text-center text-white">
          <h3><%= t "base.brand" %></h3>
          <h3><%= @brand.name %></h3>
        </div>
        <div class="card-body text-primary">
          <%= form_for(@brand) do |f| %>
            <%= render "shared/error_messages", object: f.object %>

            <%= f.label :name, t("base.name") %>
            <%= f.text_field :name, class: "form-control" %>
            <%= f.submit t("base.edit"), class: "btn btn-primary mt-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/brands/index.html.erb
<div class="container">
  <div class="row mt-4 mb-4">
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
      <div class="card ">
        <div class="card-header bg-primary text-white text-center">
          <h3><%= t "base.brands" %></h3>
        </div>
        <% if @brands.blank? %>
          <div class="card-body text-danger">
            <h4><%= t "brands.empty_brands" %></h4>
          </div>
        <% else %>
          <div class="card-body">
            <%= link_to t("base.new"), new_brand_path, class: "btn btn-outline-primary" %>
            <table class="table table-bordered mt-3">
              <thead class=" bg-primary">
                <tr class="align-middle text-center text-white">
                  <th><%= t "base.index" %></th>
                  <th><%= t "base.name" %></th>
                  <th><%= t "base.action" %></th>
                </tr>
              </thead>
              <tbody>
                <% @brands.each_with_index do |f, index| %>
                  <tr class="align-middle text-center">
                    <td><%= create_index params[:page], index, @per_page %></td>
                    <td><%= f.name %></td>
                    <td>
                      <div class="m-t-10">
                        <%= link_to t("base.edit"), edit_brand_path(f) %>
                      </div>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="mt-2 ml-4">
    <%= paginate @brands %>
  </div>
</div>

app/views/brands/new.html.erb
<div class="container mt-5">
  <div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6 offset-3">
      <div class="card">
        <div class="card-header bg-primary text-center text-white">
          <h3><%= t "base.brand" %></h3>
        </div>
        <div class="card-body text-primary">
          <%= form_for(@brand) do |f| %>
            <%= render "shared/error_messages", object: f.object %>

            <%= f.label :name, t("base.name") %>
            <%= f.text_field :name, class: "form-control" %>
            <%= f.submit t("base.add"), class: "btn btn-primary mt-3" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>